Update OrangeFox.yml

diff --git a/.github/workflows/OrangeFox.yml b/.github/workflows/OrangeFox.yml
--- a/.github/workflows/OrangeFox.yml
+++ b/.github/workflows/OrangeFox.yml
@@ -1,16 +1,20 @@
 name: OrangeFox - Build
 
-# Credits to:
-# https://github.com/TeamWin
-# https://gitlab.com/OrangeFox
-# https://github.com/azwhikaru for Recovery Builder Template
-# And all Contributors in every repositories I used
-
 on:
   workflow_dispatch:
     inputs:
+      RECOVERY_NAME:
+        description: 'Select Recovery To Build'
+        required: true
+        default: 'OFOX'
+        type: choice
+        options:
+        - TWRP
+        - OFOX
+        - PBRP
+        - SHRP
       MANIFEST_BRANCH:
-        description: 'OrangeFox Manifest Branch'
+        description: 'Recovery Manifest Branch'
         required: true
         default: '12.1'
         type: choice
@@ -18,11 +22,11 @@ on:
         - 12.1
         - 11.0
       DEVICE_TREE:
-        description: 'OrangeFox Device Tree'
+        description: 'Recovery Device Tree'
         required: true
         default: 'https://github.com/cd-Crypton/custom_recovery_tree_realme_nashc'
       DEVICE_TREE_BRANCH:
-        description: 'OrangeFox Device Tree Branch'
+        description: 'Recovery Device Tree Branch'
         required: true
         default: 'android-12.1'
       DEVICE_PATH:
@@ -41,13 +45,18 @@ on:
         options:
         - boot
         - recovery
-        - vendorboot
+        - vendor_boot
+      SEND_TELEGRAM:
+        description: 'Auto Send To Telegram'
+        required: false
+        default: true
+        type: boolean
 
 jobs:
-  build:
+  OrangeFox-Build:
     name: Build OFR by ${{ github.actor }}
     runs-on: ubuntu-latest
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: ${{ github.event.inputs.RECOVERY_NAME == 'OFOX' }}
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     permissions:
@@ -55,14 +64,27 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v4
-              
+
+    - name: Check secrets
+      id: check
+      run: |
+        if [[ -z "${{ secrets.CHAT_ID }}" ]]; then
+          echo "Build Failed, CHAT_ID not set!"
+          exit 1
+        fi
+
+        if [[ -z "${{ secrets.BOT_TOKEN }}" ]]; then
+          echo "Build Failed, BOT_TOKEN not set!"
+          exit 1
+        fi
+        
     - name: Clean-up
       uses: rokibhasansagar/slimhub_actions@main
 
     - name: Swap Space
       uses: pierotofy/set-swap-space@master
       with:
-        swap-size-gb: 12
+        swap-size-gb: 15
       
     - name: Build Environment
       run: |
@@ -77,7 +99,7 @@ jobs:
         mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
         cd ${GITHUB_WORKSPACE}/OrangeFox
         git config --global user.name "${{ github.actor }}"
-        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+        git config --global user.email "${{ github.actor }}@users.build"
         git clone https://gitlab.com/OrangeFox/sync.git -b master
         cd sync
         ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
@@ -100,9 +122,25 @@ jobs:
 
     - name: Set Release Properties
       run: |
-        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
+        echo "BUILD_DATE=$(TZ=Asia/Jakarta date +%Y%m%d)" >> $GITHUB_ENV
         cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
 
+    - name: Upload files to Telegram
+      if: github.event.inputs.SEND_TELEGRAM == 'true'
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{  secrets.CHAT_ID  }}
+        token: ${{ secrets.BOT_TOKEN }}
+        message: "
+          <pre>
+              <b>OrangeFox Recovery - Unofficial</b>
+              <b>Devices : ${{ github.event.inputs.DEVICE_NAME }}</b>
+              <b>Build Date : ${{ env.BUILD_DATE }}</b>
+          </pre> "
+        document: |
+          ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
+          ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
+     
     - name: Upload to Release
       uses: softprops/action-gh-release@v1
       with:
@@ -112,7 +150,6 @@ jobs:
         name: OrangeFox Recovery for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
         tag_name: ${{ github.run_id }}
         body: |
-          ## OrangeFox Recovery Build - Unofficial
-          Build: fox_${{ github.event.inputs.MANIFEST_BRANCH }}
-          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
-          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          ## OrangeFox Recovery - Unofficial
+          Devices : ${{ github.event.inputs.DEVICE_NAME }}
+          Build Date : ${{ env.BUILD_DATE }}
